- name: Add new gpg key for docker
  sudo: yes
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: Set docker.list for apt
  sudo: yes
  template:
    dest: /etc/apt/sources.list.d/docker.list
    src: docker.list.j2
    force: yes
- name: Update apt
  sudo: yes
  apt:
    upgrade: safe
    update_cache: yes
    state: latest
- name: Install docker
  sudo: yes
  apt:
    name: docker-engine
    state: latest
- name: Update group to enable docker without sudo
  sudo: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
- name: restart service
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: restarted
  register: docker_restart
  changed_when: False
