- name: Add new gpg key for docker
  sudo: yes
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
- name: Set docker.list for apt
  sudo: yes
  template:
    dest: /etc/apt/sources.list.d/docker.list
    src: docker.list.j2
    force: yes
- name: Update apt
  sudo: yes
  apt:
    update_cache: yes
- name: Purge for old repo
  sudo: yes
  apt:
    name: lxc-docker
    state: absent
    purge: yes
- name: Update apt
  sudo: yes
  apt:
    upgrade: safe
    state: latest
- name: Install docker
  apt:
    name: docker-engine
    state: latest
