---
- name: Update motd
  sudo: yes
  copy:
    src: motd.j2
    dest: /etc/update-motd.d/99-environment
    mode: 0755
- name: Set environment file
  sudo: yes
  copy:
    src: environment-{{env}}.j2
    dest: /etc/update-motd.d/environment
    mode: 0644

