---
- name: Verify node installation
  shell: type node
  register: verify_node
  failed_when: verify_node.rc not in [0, 1, 127]
  changed_when: verify_node.rc in [1, 127]
- name: Download node package
  when: verify_node | changed
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_{{node_version}} | bash -
- name: Install NodeJS
  become: yes
  apt:
    name: nodejs

