---
- name: Update system package
  become: yes
  apt:
    state: present
    update_cache: yes
- name: Configure resolvconf
  become: yes
  lineinfile:
    dest: /etc/resolvconf/resolv.conf.d/base
    line: 'options single-request-reopen'
  register: modify_resolvconf
- name: Update resolvconf
  when: modify_resolvconf | changed
  become: yes
  command: resolvconf -u

