# Installing pip
- name: Installing pip
  sudo: yes
  apt:
    name: python-pip
# Install docker-py to avoid ansible bug
# https://github.com/ansible/ansible-modules-core/issues/1792
- name: Install Docker py
  sudo: yes
  pip:
    name: docker-py
# pull docker image from Docker Hub
- name: verify if docker is running
  sudo: yes
  shell: service docker status
  register: docker_service_status
  failed_when: "'Docker is' not in docker_service_status.stdout"
  changed_when: "'not running' in docker_service_status.stdout"
- name: start docker service
  when: "'not running' in docker_service_status.stdout"
  sudo: yes
  shell: service docker start
  register: start_docker_service
  failed_when: start_docker_service.rc != 0
- name: Pull docker
  sudo: yes
  docker:
    registry: hub.docker.com
    image: givery/codecheck
    state: reloaded
    pull: always
  register: docker_pull
  changed_when: docker_pull.summary.pulled != 0
- name: Create cache container
  sudo: yes
  docker:
    name: cache-master
    image: givery/codecheck:latest
    state: present
    volumes:
    - /root/.npm
    - /root/.cabal
    - /root/.composer
    - /root/.gem
    - /root/.ghc
    - /root/.gradle
    - /root/.ivy2
    - /root/.m2
    - /root/.mono
    - /root/.sbt
    - /root/go
- name: Install forever
  sudo: yes
  npm:
    global: yes
    name: forever
    state: latest
    production: yes
