# Prepare test server script
- name: Prapare directory to clone
  become: yes
  file:
    state: directory
    owner: "{{ ansible_user_id }}"
    path: "{{ source_path }}"
- name: Clone whale-server
  git:
    accept_hostkey: yes
    repo: https://{{ github_token }}@github.com/givery-technology/whale-server.git
    dest: "{{ source_path }}"
    recursive: no
