# Prepare test server script
- name: Prapare directory to clone
  sudo: yes
  file:
    state: directory
    owner: "{{ ansible_user_id }}"
    path: "{{ source_path }}"
- name: Copy whale-server
  copy:
    src: /tmp/whale-server
    dest: "{{ source_path }}"
#- name: npm install
#  npm:
#    path: "{{ source_path }}"
#    state: present
#- name: Install init config
#  sudo: yes
#  template:
#    src: codecheck.conf.j2
#    dest: /etc/init/codecheck.conf
#- name: Start test run server
#  sudo: yes
#  service:
#    name: codecheck
#    state: started
#- name: Cron for docker
#  cron:
#    name: "Clean up docker containers"
#    minute: "0"
#    hour: "*/3"
#    job: "docker rm $(docker ps -f status=exited -q)"
#    state: present
