# Prepare test server script
- name: Prapare directory to clone
  sudo: yes
  file:
    state: directory
    owner: "{{ os_user }}"
    path: "{{clone_path}}"
- name: Clone test server scripts
  git:
    accept_hostkey: yes
    repo: https://{{github_token}}@github.com/givery-technology/code-testserver.git
    dest: "{{clone_path}}"
    recursive: no
      # Set to ignore submodule; codetest-env is currently private and can't install by submodule
